In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import sklearn as sk
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import explained_variance_score, make_scorer
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold # cross validation
from sklearn.model_selection import learning_curve
from sklearn.model_selection import ShuffleSplit # cross validation 
from sklearn.metrics import auc
import itertools
from sklearn.feature_selection import RFE

# models
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network  import MLPClassifier
from sklearn.svm import SVC

In [5]:
df = pd.read_csv("dataset-kendra-c.csv", delimiter=',')
print(df.duplicated().sum())
df = df.drop_duplicates()
df

499

     C1  C2  C3  C4  C5  C6  C7  C8  C9  C10  Vulnerable?
0     7   0   0   0   0  -1   0  -1  -1   -1            0
2     7   0   0   0   0  -1   1  -1  -1   -1            1
8     1   0   0   0   0   0  -1  -1  -1   -1            0
70    1   0   0   0   0  -1  -1  -1   0   -1            0
245   1   0   0   0   0   1  -1  -1  -1   -1            1
342   1   0   0   0   0  -1  -1  -1   1   -1            1